# Generated by Django 2.1.2 on 2019-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=150)),
                ('balance', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
